# fly.toml app configuration file generated for next-playground-sqlite on 2023-06-17T22:10:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "next-playground-sqlite"
primary_region = "waw"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "3s"
    grace_period = "5s"
    restart_limit = 5

  [[services.http_checks]]
    interval = "5s"
    timeout = "3s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/api/health"
