# fly.toml app configuration file generated for next-playground on 2023-06-14T23:48:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "next-playground"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
