import { Inter } from "next/font/google";

import "~/app/globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => (
  <html className={inter.variable} lang="en">
    <body className="p-8">{children}</body>
  </html>
);

export default MainLayout;
